### ISSUE TITLE
Java 6

### ISSUE THREAD

**Issue by ghost** [jirutka/embedmongo-spring#3]
Hello,

It seems that embedmongo-spring has been compiled with a JDK compliance above Java 6, leading to the following error at runtime with Java 6.

java.lang.UnsupportedClassVersionError: cz/jirutka/spring/embedmongo/EmbeddedMongoFactoryBean : Unsupported major.minor version 51.0

Is it possible to downgrade this aspect of compilation please ?
Regards,
JavaPelp

**Comment by belon** [comment]
Archive in maven central is compiled with JDK7, manifest file:
Manifest-Version: 1.0
Built-By: jimmy
Build-Jdk: 1.7.0-u14-b15
Created-By: Apache Maven 3.1.1
Archiver-Version: Plexus Archiver

Downloaded from: https://repo1.maven.org/maven2/cz/jirutka/spring/embedmongo-spring/1.2.1/

**Comment by jirutka** [comment]
@belon Yeah, but what's the problem?

**Comment by belon** [comment]
The problem is that it is not compiled with JDK6 so it can not be used in project which need to be run on JDK6.

**Comment by jirutka** [comment]
Ah, I forgot that I’ve changed it later. The last version compatible with Java 1.6 is 1.2.2, so if you really wanna use ancient and unsupported Java 6, use embedmongo-spring 1.2.2.

**Comment by belon** [comment]
I don't wanna use it but for some reason I need to. It also doesn't work and MANIFEST contains JDK7

Manifest-Version: 1.0
Implementation-Title: EmbedMongo - Spring Factory
Implementation-Version: 1.2.2
Implementation-Vendor-Id: cz.jirutka.spring
Built-By: jimmy
Build-Jdk: 1.7.0-u14-b15
Created-By: Apache Maven 3.2.1
Implementation-Build: 90a613974b276696441e6f012018f9857877e53a
Built-Date: 2014-06-26T19:07:27+0200
Archiver-Version: Plexus Archiver
